import { ProductLegacy, UserLegacy } from './types';

export const mockProducts: ProductLegacy[] = [
  {
    id: '1',
    name: 'Premium Cotton T-Shirt',
    slug: 'premium-cotton-t-shirt',
    description: 'High-quality cotton t-shirt perfect for everyday wear. Made from 100% organic cotton with a comfortable fit.',
    tags: ['casual', 'cotton', 'trending'],
    price: 29.99,
    colour: 'blue',
    size: 'md',
    images: [
      'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    inStock: true,
    totalStock: 50,
    soldCount: 120,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Classic Denim Jacket',
    slug: 'classic-denim-jacket',
    description: 'Timeless denim jacket that pairs well with any outfit. Durable construction with vintage styling.',
    tags: ['denim', 'jacket', 'popular'],
    price: 79.99,
    colour: 'indigo',
    size: 'lg',
    images: [
      'https://images.pexels.com/photos/1124465/pexels-photo-1124465.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    inStock: true,
    totalStock: 30,
    soldCount: 85,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    name: 'Wool Blend Sweater',
    slug: 'wool-blend-sweater',
    description: 'Cozy wool blend sweater perfect for cold weather. Soft texture with excellent warmth retention.',
    tags: ['wool', 'winter', 'trending'],
    price: 59.99,
    colour: 'gray',
    size: 'md',
    images: [
      'https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    inStock: true,
    totalStock: 25,
    soldCount: 200,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: '4',
    name: 'Athletic Running Shorts',
    slug: 'athletic-running-shorts',
    description: 'Lightweight running shorts with moisture-wicking fabric. Perfect for workouts and outdoor activities.',
    tags: ['athletic', 'running', 'popular'],
    price: 24.99,
    colour: 'black',
    size: 'sm',
    images: [
      'https://images.pexels.com/photos/7432165/pexels-photo-7432165.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    inStock: true,
    totalStock: 40,
    soldCount: 150,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    name: 'Casual Button-Up Shirt',
    slug: 'casual-button-up-shirt',
    description: 'Versatile button-up shirt suitable for both casual and semi-formal occasions. Made from breathable cotton blend.',
    tags: ['shirt', 'casual', 'formal'],
    price: 44.99,
    colour: 'white',
    size: 'lg',
    images: [
      'https://images.pexels.com/photos/1124466/pexels-photo-1124466.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    inStock: true,
    totalStock: 35,
    soldCount: 95,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: '6',
    name: 'Leather Ankle Boots',
    slug: 'leather-ankle-boots',
    description: 'Stylish leather ankle boots with premium craftsmanship. Perfect for both casual and dressy outfits.',
    tags: ['boots', 'leather', 'trending'],
    price: 129.99,
    colour: 'brown',
    size: 'md',
    images: [
      'https://images.pexels.com/photos/1449667/pexels-photo-1449667.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    inStock: true,
    totalStock: 20,
    soldCount: 75,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
];

export const mockUsers: UserLegacy[] = [
  {
    id: '1',
    username: 'admin',
    email: 'admin@example.com',
    phone: '+1234567890',
    role: 'admin',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    username: 'john_doe',
    email: 'john@example.com',
    phone: '+1987654321',
    role: 'user',
    createdAt: new Date('2024-01-02'),
  },
];